---
fixtures:
  forge_modules:
    'stdlib':
      repo: 'puppetlabs/stdlib'
    'concat':
      repo: 'puppetlabs/concat'
    'systemd':
      repo: 'camptocamp/systemd'
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'