---
mock_with: ':rspec'
use_litmus: true
changelog_user: rtib
changelog_project: puppet-geoip
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.build = false
        t.tag_message_pattern = "Release v%s"
      end
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '= 1.15.2'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
