---
mock_with: ':rspec'
use_litmus: true
changelog_user: rtib
changelog_project: puppet-geoip
# Rakefile:
#   extras:
#     - |
#       Blacksmith::RakeTask.new do |t|
#         t.build = false
#         t.tag_message_pattern = "Release v%s"
#       end
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: puppet-blacksmith
      - gem: 'github_changelog_generator'
        version: '>= 1.16.1'
