---
name: CI-spec
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

env:
  HONEYCOMB_WRITEKEY: "${{ secrets.HONEYCOMB_WRITEKEY }}"
  HONEYCOMB_DATASET: puppet-geoip

jobs:
  setup_matrix:
    name: 'Setup test matrix'
    runs-on: ubuntu-latest
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}
      acceptance_matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Activate Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Get matrix
        id: get-matrix
        run: bundle exec matrix_from_metadata_v2

  spec:
    runs-on: ubuntu-latest
    needs: setup_matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup_matrix.outputs.spec_matrix) }}
    env:
      PUPPET_GEM_VERSION: "${{ matrix.puppet_version }}"
    name: Spec tests for Puppet ${{ matrix.puppet_version }} on Ruby ${{ matrix.ruby_version }}
    steps:
      - uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Prepare environment
        run: |
          bundle config set --local without 'system_tests'
          bundle install

      - name: Spec tests
        run: bundle exec rake parallel_spec
