---
name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

env:
  HONEYCOMB_WRITEKEY: "${{ secrets.HONEYCOMB_WRITEKEY }}"
  HONEYCOMB_DATASET: puppet-geoip

jobs:
  setup_matrix:
    name: 'Setup test matrix'
    runs-on: ubuntu-latest
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}
      acceptance_matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Activate Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: false

      - name: Prepare environment
        run: |
          bundle config set --local without 'release'
          bundle install

      - name: Bundler environment
        run: bundle env

      - name: Get matrix
        id: get-matrix
        run: bundle exec matrix_from_metadata_v2

  spec:
    name: Spec tests for Puppet ${{ matrix.puppet_version }} on Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    needs: setup_matrix
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup_matrix.outputs.spec_matrix) }}
    env:
      PUPPET_GEM_VERSION: "${{ matrix.puppet_version }}"
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
      - uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Bundler environment
        run: bundle env

      - name: Run static & syntax tests
        run: bundle exec rake syntax lint metadata_lint rubocop

      - name: Run spec tests
        run: bundle exec rake parallel_spec

  acceptance:
    needs: [ setup_matrix, spec ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup_matrix.outputs.acceptance_matrix) }}
    name: Litmus tests for ${{ matrix.platforms.label }} with ${{ matrix.collection }}
    steps:
      - uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Prepare environment
        run: |
          bundle config set --local with 'system_tests'
          bundle install

      - name: Provision test environment
        run: bundle exec rake 'litmus:provision[${{ matrix.platforms.provider }},${{ matrix.platforms.image }}]'

      - name: Install Agent
        run: bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'

      - name: Install Module
        run: bundle exec rake 'litmus:install_module'

      - name: Running acceptance tests
        run: bundle exec rake 'litmus:acceptance:parallel'
        env:
          MM_USERID: ${{ secrets.MM_USERID }}
          MM_LICENSEKEY_LT311: ${{ secrets.MM_LICENSEKEY_LT311 }}
          MM_LICENSEKEY_GE311: ${{ secrets.MM_LICENSEKEY_GE311}}
